/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmbAmbulanceWlList {
    }
}
declare global {
    interface HTMLAmbAmbulanceWlListElement extends Components.AmbAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLAmbAmbulanceWlListElement: {
        prototype: HTMLAmbAmbulanceWlListElement;
        new (): HTMLAmbAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "amb-ambulance-wl-list": HTMLAmbAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface AmbAmbulanceWlList {
    }
    interface IntrinsicElements {
        "amb-ambulance-wl-list": AmbAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "amb-ambulance-wl-list": LocalJSX.AmbAmbulanceWlList & JSXBase.HTMLAttributes<HTMLAmbAmbulanceWlListElement>;
        }
    }
}
